name: Publish Storybook

on:
  push:
    branches:
    - 'main'
    - 'feature/storybook'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        install_command: yarn install
        build_command: yarn build-storybook
        path: storybook-static
        checkout: false
        caching: true